//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HuergoMotorsEcommerce.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAccesoriosByModeloOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccesoriosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVehiculosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearVentaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::HuergoMotorsEcommerce.Properties.Settings.Default.HuergoMotorsEcommerce_WebService_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAccesoriosByModeloCompletedEventHandler GetAccesoriosByModeloCompleted;
        
        /// <remarks/>
        public event GetAccesoriosCompletedEventHandler GetAccesoriosCompleted;
        
        /// <remarks/>
        public event GetClientesCompletedEventHandler GetClientesCompleted;
        
        /// <remarks/>
        public event GetVehiculosCompletedEventHandler GetVehiculosCompleted;
        
        /// <remarks/>
        public event GetVentasCompletedEventHandler GetVentasCompleted;
        
        /// <remarks/>
        public event CrearVentaCompletedEventHandler CrearVentaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccesoriosByModelo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccesoriosDTO[] GetAccesoriosByModelo(string filtro) {
            object[] results = this.Invoke("GetAccesoriosByModelo", new object[] {
                        filtro});
            return ((AccesoriosDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccesoriosByModeloAsync(string filtro) {
            this.GetAccesoriosByModeloAsync(filtro, null);
        }
        
        /// <remarks/>
        public void GetAccesoriosByModeloAsync(string filtro, object userState) {
            if ((this.GetAccesoriosByModeloOperationCompleted == null)) {
                this.GetAccesoriosByModeloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccesoriosByModeloOperationCompleted);
            }
            this.InvokeAsync("GetAccesoriosByModelo", new object[] {
                        filtro}, this.GetAccesoriosByModeloOperationCompleted, userState);
        }
        
        private void OnGetAccesoriosByModeloOperationCompleted(object arg) {
            if ((this.GetAccesoriosByModeloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccesoriosByModeloCompleted(this, new GetAccesoriosByModeloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccesorios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccesoriosDTO[] GetAccesorios() {
            object[] results = this.Invoke("GetAccesorios", new object[0]);
            return ((AccesoriosDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccesoriosAsync() {
            this.GetAccesoriosAsync(null);
        }
        
        /// <remarks/>
        public void GetAccesoriosAsync(object userState) {
            if ((this.GetAccesoriosOperationCompleted == null)) {
                this.GetAccesoriosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccesoriosOperationCompleted);
            }
            this.InvokeAsync("GetAccesorios", new object[0], this.GetAccesoriosOperationCompleted, userState);
        }
        
        private void OnGetAccesoriosOperationCompleted(object arg) {
            if ((this.GetAccesoriosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccesoriosCompleted(this, new GetAccesoriosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientesDTO[] GetClientes() {
            object[] results = this.Invoke("GetClientes", new object[0]);
            return ((ClientesDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClientesAsync() {
            this.GetClientesAsync(null);
        }
        
        /// <remarks/>
        public void GetClientesAsync(object userState) {
            if ((this.GetClientesOperationCompleted == null)) {
                this.GetClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientesOperationCompleted);
            }
            this.InvokeAsync("GetClientes", new object[0], this.GetClientesOperationCompleted, userState);
        }
        
        private void OnGetClientesOperationCompleted(object arg) {
            if ((this.GetClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientesCompleted(this, new GetClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVehiculos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VehiculosDTO[] GetVehiculos() {
            object[] results = this.Invoke("GetVehiculos", new object[0]);
            return ((VehiculosDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVehiculosAsync() {
            this.GetVehiculosAsync(null);
        }
        
        /// <remarks/>
        public void GetVehiculosAsync(object userState) {
            if ((this.GetVehiculosOperationCompleted == null)) {
                this.GetVehiculosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVehiculosOperationCompleted);
            }
            this.InvokeAsync("GetVehiculos", new object[0], this.GetVehiculosOperationCompleted, userState);
        }
        
        private void OnGetVehiculosOperationCompleted(object arg) {
            if ((this.GetVehiculosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVehiculosCompleted(this, new GetVehiculosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VentasDTO[] GetVentas(int IdCliente) {
            object[] results = this.Invoke("GetVentas", new object[] {
                        IdCliente});
            return ((VentasDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVentasAsync(int IdCliente) {
            this.GetVentasAsync(IdCliente, null);
        }
        
        /// <remarks/>
        public void GetVentasAsync(int IdCliente, object userState) {
            if ((this.GetVentasOperationCompleted == null)) {
                this.GetVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVentasOperationCompleted);
            }
            this.InvokeAsync("GetVentas", new object[] {
                        IdCliente}, this.GetVentasOperationCompleted, userState);
        }
        
        private void OnGetVentasOperationCompleted(object arg) {
            if ((this.GetVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVentasCompleted(this, new GetVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearVenta(int IdVehiculo, int IdCliente, int IdVendedor, AccesoriosDTO[] dtosAccesorios, string obs, decimal tot, int stock) {
            object[] results = this.Invoke("CrearVenta", new object[] {
                        IdVehiculo,
                        IdCliente,
                        IdVendedor,
                        dtosAccesorios,
                        obs,
                        tot,
                        stock});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearVentaAsync(int IdVehiculo, int IdCliente, int IdVendedor, AccesoriosDTO[] dtosAccesorios, string obs, decimal tot, int stock) {
            this.CrearVentaAsync(IdVehiculo, IdCliente, IdVendedor, dtosAccesorios, obs, tot, stock, null);
        }
        
        /// <remarks/>
        public void CrearVentaAsync(int IdVehiculo, int IdCliente, int IdVendedor, AccesoriosDTO[] dtosAccesorios, string obs, decimal tot, int stock, object userState) {
            if ((this.CrearVentaOperationCompleted == null)) {
                this.CrearVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearVentaOperationCompleted);
            }
            this.InvokeAsync("CrearVenta", new object[] {
                        IdVehiculo,
                        IdCliente,
                        IdVendedor,
                        dtosAccesorios,
                        obs,
                        tot,
                        stock}, this.CrearVentaOperationCompleted, userState);
        }
        
        private void OnCrearVentaOperationCompleted(object arg) {
            if ((this.CrearVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearVentaCompleted(this, new CrearVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccesoriosDTO {
        
        private int idField;
        
        private string nombreField;
        
        private string modeloField;
        
        private decimal precioVentaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VentasDTO {
        
        private int idField;
        
        private System.DateTime fechaField;
        
        private string vehiculoField;
        
        private string clienteField;
        
        private string vendedorField;
        
        private string observacionesField;
        
        private decimal totalField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string Vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
            }
        }
        
        /// <remarks/>
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public string Vendedor {
            get {
                return this.vendedorField;
            }
            set {
                this.vendedorField = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VehiculosDTO {
        
        private int idField;
        
        private string tipoField;
        
        private string modeloField;
        
        private decimal precioVentaField;
        
        private int stockDisponibleField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
            }
        }
        
        /// <remarks/>
        public int StockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientesDTO {
        
        private int idField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private string emailField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAccesoriosByModeloCompletedEventHandler(object sender, GetAccesoriosByModeloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccesoriosByModeloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccesoriosByModeloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccesoriosDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccesoriosDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAccesoriosCompletedEventHandler(object sender, GetAccesoriosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccesoriosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccesoriosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccesoriosDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccesoriosDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetClientesCompletedEventHandler(object sender, GetClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientesDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientesDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetVehiculosCompletedEventHandler(object sender, GetVehiculosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVehiculosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVehiculosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VehiculosDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VehiculosDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetVentasCompletedEventHandler(object sender, GetVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VentasDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VentasDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CrearVentaCompletedEventHandler(object sender, CrearVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591