//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HuergoMotorsEcommerce.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DTOBase))]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IniciarSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVehiculosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVehiculosFiltradosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVehiculosbyIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccesoriosByModeloOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccesoriosByIdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback carritoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::HuergoMotorsEcommerce.Properties.Settings.Default.HuergoMotorsEcommerce_WebService_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IniciarSesionCompletedEventHandler IniciarSesionCompleted;
        
        /// <remarks/>
        public event RegistrarUsuarioCompletedEventHandler RegistrarUsuarioCompleted;
        
        /// <remarks/>
        public event GetVehiculosCompletedEventHandler GetVehiculosCompleted;
        
        /// <remarks/>
        public event GetVehiculosFiltradosCompletedEventHandler GetVehiculosFiltradosCompleted;
        
        /// <remarks/>
        public event GetVehiculosbyIdCompletedEventHandler GetVehiculosbyIdCompleted;
        
        /// <remarks/>
        public event GetAccesoriosByModeloCompletedEventHandler GetAccesoriosByModeloCompleted;
        
        /// <remarks/>
        public event CrearVentaCompletedEventHandler CrearVentaCompleted;
        
        /// <remarks/>
        public event GetVentasCompletedEventHandler GetVentasCompleted;
        
        /// <remarks/>
        public event ActualizarUsuarioCompletedEventHandler ActualizarUsuarioCompleted;
        
        /// <remarks/>
        public event GetClientesCompletedEventHandler GetClientesCompleted;
        
        /// <remarks/>
        public event GetAccesoriosByIdsCompletedEventHandler GetAccesoriosByIdsCompleted;
        
        /// <remarks/>
        public event carritoCompletedEventHandler carritoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IniciarSesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientesDTO IniciarSesion(string usuario, string contraseña) {
            object[] results = this.Invoke("IniciarSesion", new object[] {
                        usuario,
                        contraseña});
            return ((ClientesDTO)(results[0]));
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string usuario, string contraseña) {
            this.IniciarSesionAsync(usuario, contraseña, null);
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string usuario, string contraseña, object userState) {
            if ((this.IniciarSesionOperationCompleted == null)) {
                this.IniciarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarSesionOperationCompleted);
            }
            this.InvokeAsync("IniciarSesion", new object[] {
                        usuario,
                        contraseña}, this.IniciarSesionOperationCompleted, userState);
        }
        
        private void OnIniciarSesionOperationCompleted(object arg) {
            if ((this.IniciarSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarSesionCompleted(this, new IniciarSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientesDTO RegistrarUsuario(ClientesDTO dto) {
            object[] results = this.Invoke("RegistrarUsuario", new object[] {
                        dto});
            return ((ClientesDTO)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAsync(ClientesDTO dto) {
            this.RegistrarUsuarioAsync(dto, null);
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAsync(ClientesDTO dto, object userState) {
            if ((this.RegistrarUsuarioOperationCompleted == null)) {
                this.RegistrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("RegistrarUsuario", new object[] {
                        dto}, this.RegistrarUsuarioOperationCompleted, userState);
        }
        
        private void OnRegistrarUsuarioOperationCompleted(object arg) {
            if ((this.RegistrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarUsuarioCompleted(this, new RegistrarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVehiculos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AutoConFoto[] GetVehiculos() {
            object[] results = this.Invoke("GetVehiculos", new object[0]);
            return ((AutoConFoto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVehiculosAsync() {
            this.GetVehiculosAsync(null);
        }
        
        /// <remarks/>
        public void GetVehiculosAsync(object userState) {
            if ((this.GetVehiculosOperationCompleted == null)) {
                this.GetVehiculosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVehiculosOperationCompleted);
            }
            this.InvokeAsync("GetVehiculos", new object[0], this.GetVehiculosOperationCompleted, userState);
        }
        
        private void OnGetVehiculosOperationCompleted(object arg) {
            if ((this.GetVehiculosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVehiculosCompleted(this, new GetVehiculosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVehiculosFiltrados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AutoConFoto[] GetVehiculosFiltrados(string filtro, string valor) {
            object[] results = this.Invoke("GetVehiculosFiltrados", new object[] {
                        filtro,
                        valor});
            return ((AutoConFoto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVehiculosFiltradosAsync(string filtro, string valor) {
            this.GetVehiculosFiltradosAsync(filtro, valor, null);
        }
        
        /// <remarks/>
        public void GetVehiculosFiltradosAsync(string filtro, string valor, object userState) {
            if ((this.GetVehiculosFiltradosOperationCompleted == null)) {
                this.GetVehiculosFiltradosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVehiculosFiltradosOperationCompleted);
            }
            this.InvokeAsync("GetVehiculosFiltrados", new object[] {
                        filtro,
                        valor}, this.GetVehiculosFiltradosOperationCompleted, userState);
        }
        
        private void OnGetVehiculosFiltradosOperationCompleted(object arg) {
            if ((this.GetVehiculosFiltradosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVehiculosFiltradosCompleted(this, new GetVehiculosFiltradosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVehiculosbyId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AutoConFoto GetVehiculosbyId(int Id) {
            object[] results = this.Invoke("GetVehiculosbyId", new object[] {
                        Id});
            return ((AutoConFoto)(results[0]));
        }
        
        /// <remarks/>
        public void GetVehiculosbyIdAsync(int Id) {
            this.GetVehiculosbyIdAsync(Id, null);
        }
        
        /// <remarks/>
        public void GetVehiculosbyIdAsync(int Id, object userState) {
            if ((this.GetVehiculosbyIdOperationCompleted == null)) {
                this.GetVehiculosbyIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVehiculosbyIdOperationCompleted);
            }
            this.InvokeAsync("GetVehiculosbyId", new object[] {
                        Id}, this.GetVehiculosbyIdOperationCompleted, userState);
        }
        
        private void OnGetVehiculosbyIdOperationCompleted(object arg) {
            if ((this.GetVehiculosbyIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVehiculosbyIdCompleted(this, new GetVehiculosbyIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccesoriosByModelo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccesoriosDTO[] GetAccesoriosByModelo(string filtro) {
            object[] results = this.Invoke("GetAccesoriosByModelo", new object[] {
                        filtro});
            return ((AccesoriosDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccesoriosByModeloAsync(string filtro) {
            this.GetAccesoriosByModeloAsync(filtro, null);
        }
        
        /// <remarks/>
        public void GetAccesoriosByModeloAsync(string filtro, object userState) {
            if ((this.GetAccesoriosByModeloOperationCompleted == null)) {
                this.GetAccesoriosByModeloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccesoriosByModeloOperationCompleted);
            }
            this.InvokeAsync("GetAccesoriosByModelo", new object[] {
                        filtro}, this.GetAccesoriosByModeloOperationCompleted, userState);
        }
        
        private void OnGetAccesoriosByModeloOperationCompleted(object arg) {
            if ((this.GetAccesoriosByModeloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccesoriosByModeloCompleted(this, new GetAccesoriosByModeloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearVenta(int IdVehiculo, int IdCliente, int IdVendedor, AccesoriosDTO[] dtosAccesorios, string obs, decimal tot) {
            object[] results = this.Invoke("CrearVenta", new object[] {
                        IdVehiculo,
                        IdCliente,
                        IdVendedor,
                        dtosAccesorios,
                        obs,
                        tot});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearVentaAsync(int IdVehiculo, int IdCliente, int IdVendedor, AccesoriosDTO[] dtosAccesorios, string obs, decimal tot) {
            this.CrearVentaAsync(IdVehiculo, IdCliente, IdVendedor, dtosAccesorios, obs, tot, null);
        }
        
        /// <remarks/>
        public void CrearVentaAsync(int IdVehiculo, int IdCliente, int IdVendedor, AccesoriosDTO[] dtosAccesorios, string obs, decimal tot, object userState) {
            if ((this.CrearVentaOperationCompleted == null)) {
                this.CrearVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearVentaOperationCompleted);
            }
            this.InvokeAsync("CrearVenta", new object[] {
                        IdVehiculo,
                        IdCliente,
                        IdVendedor,
                        dtosAccesorios,
                        obs,
                        tot}, this.CrearVentaOperationCompleted, userState);
        }
        
        private void OnCrearVentaOperationCompleted(object arg) {
            if ((this.CrearVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearVentaCompleted(this, new CrearVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VentasDTO[] GetVentas(int IdCliente) {
            object[] results = this.Invoke("GetVentas", new object[] {
                        IdCliente});
            return ((VentasDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVentasAsync(int IdCliente) {
            this.GetVentasAsync(IdCliente, null);
        }
        
        /// <remarks/>
        public void GetVentasAsync(int IdCliente, object userState) {
            if ((this.GetVentasOperationCompleted == null)) {
                this.GetVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVentasOperationCompleted);
            }
            this.InvokeAsync("GetVentas", new object[] {
                        IdCliente}, this.GetVentasOperationCompleted, userState);
        }
        
        private void OnGetVentasOperationCompleted(object arg) {
            if ((this.GetVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVentasCompleted(this, new GetVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientesDTO ActualizarUsuario(ClientesDTO cliente) {
            object[] results = this.Invoke("ActualizarUsuario", new object[] {
                        cliente});
            return ((ClientesDTO)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarUsuarioAsync(ClientesDTO cliente) {
            this.ActualizarUsuarioAsync(cliente, null);
        }
        
        /// <remarks/>
        public void ActualizarUsuarioAsync(ClientesDTO cliente, object userState) {
            if ((this.ActualizarUsuarioOperationCompleted == null)) {
                this.ActualizarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ActualizarUsuario", new object[] {
                        cliente}, this.ActualizarUsuarioOperationCompleted, userState);
        }
        
        private void OnActualizarUsuarioOperationCompleted(object arg) {
            if ((this.ActualizarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarUsuarioCompleted(this, new ActualizarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientesDTO[] GetClientes() {
            object[] results = this.Invoke("GetClientes", new object[0]);
            return ((ClientesDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClientesAsync() {
            this.GetClientesAsync(null);
        }
        
        /// <remarks/>
        public void GetClientesAsync(object userState) {
            if ((this.GetClientesOperationCompleted == null)) {
                this.GetClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientesOperationCompleted);
            }
            this.InvokeAsync("GetClientes", new object[0], this.GetClientesOperationCompleted, userState);
        }
        
        private void OnGetClientesOperationCompleted(object arg) {
            if ((this.GetClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientesCompleted(this, new GetClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccesoriosByIds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccesoriosDTO[] GetAccesoriosByIds(int[] Ids) {
            object[] results = this.Invoke("GetAccesoriosByIds", new object[] {
                        Ids});
            return ((AccesoriosDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccesoriosByIdsAsync(int[] Ids) {
            this.GetAccesoriosByIdsAsync(Ids, null);
        }
        
        /// <remarks/>
        public void GetAccesoriosByIdsAsync(int[] Ids, object userState) {
            if ((this.GetAccesoriosByIdsOperationCompleted == null)) {
                this.GetAccesoriosByIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccesoriosByIdsOperationCompleted);
            }
            this.InvokeAsync("GetAccesoriosByIds", new object[] {
                        Ids}, this.GetAccesoriosByIdsOperationCompleted, userState);
        }
        
        private void OnGetAccesoriosByIdsOperationCompleted(object arg) {
            if ((this.GetAccesoriosByIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccesoriosByIdsCompleted(this, new GetAccesoriosByIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/carrito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CarritoDTO carrito() {
            object[] results = this.Invoke("carrito", new object[0]);
            return ((CarritoDTO)(results[0]));
        }
        
        /// <remarks/>
        public void carritoAsync() {
            this.carritoAsync(null);
        }
        
        /// <remarks/>
        public void carritoAsync(object userState) {
            if ((this.carritoOperationCompleted == null)) {
                this.carritoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncarritoOperationCompleted);
            }
            this.InvokeAsync("carrito", new object[0], this.carritoOperationCompleted, userState);
        }
        
        private void OncarritoOperationCompleted(object arg) {
            if ((this.carritoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.carritoCompleted(this, new carritoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientesDTO : DTOBase {
        
        private bool clientesField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private string emailField;
        
        private string usuarioField;
        
        private string contraseñaField;
        
        /// <remarks/>
        public bool Clientes {
            get {
                return this.clientesField;
            }
            set {
                this.clientesField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CarritoDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VentasDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccesoriosDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehiculosImagenesDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehiculosDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientesDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class DTOBase {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoConFoto {
        
        private VehiculosDTO vehiculoField;
        
        private VehiculosImagenesDTO[] fotosField;
        
        /// <remarks/>
        public VehiculosDTO Vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
            }
        }
        
        /// <remarks/>
        public VehiculosImagenesDTO[] Fotos {
            get {
                return this.fotosField;
            }
            set {
                this.fotosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VehiculosDTO : DTOBase {
        
        private bool vehiculosField;
        
        private string tipoField;
        
        private string modeloField;
        
        private decimal precioVentaField;
        
        private int stockDisponibleField;
        
        private string descripcionField;
        
        /// <remarks/>
        public bool Vehiculos {
            get {
                return this.vehiculosField;
            }
            set {
                this.vehiculosField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
            }
        }
        
        /// <remarks/>
        public int StockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VehiculosImagenesDTO : DTOBase {
        
        private int idVehiculoField;
        
        private byte[] fotoField;
        
        /// <remarks/>
        public int IdVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                this.idVehiculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CarritoDTO : DTOBase {
        
        private AutoConFoto vehiculoField;
        
        private AccesoriosDTO[] accesoriosField;
        
        /// <remarks/>
        public AutoConFoto Vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
            }
        }
        
        /// <remarks/>
        public AccesoriosDTO[] Accesorios {
            get {
                return this.accesoriosField;
            }
            set {
                this.accesoriosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccesoriosDTO : DTOBase {
        
        private bool accesoriosField;
        
        private string nombreField;
        
        private string modeloField;
        
        private decimal precioVentaField;
        
        /// <remarks/>
        public bool Accesorios {
            get {
                return this.accesoriosField;
            }
            set {
                this.accesoriosField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VentasDTO : DTOBase {
        
        private bool ventasField;
        
        private System.DateTime fechaField;
        
        private string vehiculoField;
        
        private string clienteField;
        
        private string vendedorField;
        
        private string observacionesField;
        
        private decimal totalField;
        
        /// <remarks/>
        public bool Ventas {
            get {
                return this.ventasField;
            }
            set {
                this.ventasField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string Vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
            }
        }
        
        /// <remarks/>
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public string Vendedor {
            get {
                return this.vendedorField;
            }
            set {
                this.vendedorField = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IniciarSesionCompletedEventHandler(object sender, IniciarSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientesDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientesDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegistrarUsuarioCompletedEventHandler(object sender, RegistrarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientesDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientesDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetVehiculosCompletedEventHandler(object sender, GetVehiculosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVehiculosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVehiculosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AutoConFoto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AutoConFoto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetVehiculosFiltradosCompletedEventHandler(object sender, GetVehiculosFiltradosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVehiculosFiltradosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVehiculosFiltradosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AutoConFoto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AutoConFoto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetVehiculosbyIdCompletedEventHandler(object sender, GetVehiculosbyIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVehiculosbyIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVehiculosbyIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AutoConFoto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AutoConFoto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAccesoriosByModeloCompletedEventHandler(object sender, GetAccesoriosByModeloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccesoriosByModeloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccesoriosByModeloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccesoriosDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccesoriosDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CrearVentaCompletedEventHandler(object sender, CrearVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetVentasCompletedEventHandler(object sender, GetVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VentasDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VentasDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ActualizarUsuarioCompletedEventHandler(object sender, ActualizarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientesDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientesDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClientesCompletedEventHandler(object sender, GetClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientesDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientesDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAccesoriosByIdsCompletedEventHandler(object sender, GetAccesoriosByIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccesoriosByIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccesoriosByIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccesoriosDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccesoriosDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void carritoCompletedEventHandler(object sender, carritoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class carritoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal carritoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CarritoDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CarritoDTO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591